var datas = {
	file: [
	{
		'id': '1',
		'src': 'img/F16.png',
		'title': 'AZUKI',
		'fa':'fa-weixin'
	}, 
	{
		'id': '2',
		'src': 'img/F15.png',
		'title': 'THE ONE',
		'fa':'fa-snowflake-o'
	},
	{
		'id': '4',
		'src': 'img/F10.jpg',
		'title': 'SUNNY ',
		'fa':'fa-comment-o'		
	}
	]
}
var Src={
	file:[
		{	
			'img':'img/B01.jpg',
			'auther':'唐七',
			'title':'三生三世十里桃花',
			'money':'¥6.93',
			'pid':'0',
			'parent':'新星出版社'		
		},
		{
			'img':'img/B02.jpg',
			'auther':'罗振宇',
			'title':'时间的朋友',
			'money':'¥6.93',
			'pid':'0',
			'parent':'新星出版社'
		},
		{
			'img':'img/B03.jpg',
			'auther':'【以色列】尤瓦尔',
			'title':'未来简史：从智人到智神',
			'money':'¥40.80',
			'pid':'0',
			'parent':'新星出版社'
		},
		{
			'img':'img/B04.jpg',
			'auther':'vivibear',
			'title':'寻找前世之旅',
			'money':'¥4.99'	,
			'pid':'0',
			'parent':'新星出版社'
		},
		{
			'img':'img/B05.jpg',
			'auther':'唐七',
			'title':'三生三世枕上书 上篇',
			'money':'¥6.93',
			'pid':'1',
			'parent':'读客'
		},	
		{
			'img':'img/B06.jpg',
			'auther':'陈睿潼',
			'title':'做自己的天使投资人',
			'money':'¥29.90',
			'pid':'1',
			'parent':'读客'
		},	
		{
			'img':'img/B07.jpg',
			'auther':'角男',
			'title':'雨中你的自由泳非常美丽',
			'money':'¥12.60',
			'pid':'1',
			'parent':'读客'
		},	
		{
			'img':'img/B08.jpg',
			'auther':'【德】马丁.瓦尔',
			'title':'恋爱中的男人',
			'money':'¥7.63',
			'pid':'1',
			'parent':'读客'
		},	
		{
			'img':'img/B09.jpg',
			'auther':'木浮生',
			'title':'犹带昭阳',
			'money':'¥12.63',
			'pid':'2',
			'parent':'中信出版集团'
		},	
		{
			'img':'img/B10.jpg',
			'auther':'唐缺',
			'title':'觉醒日3',
			'money':'¥9.9',
			'pid':'2',
			'parent':'中信出版集团'
		},
		{
			'img':'img/B11.jpg',
			'auther':'花火工作室',
			'title':'花火201610B',
			'money':'¥1.99',
			'pid':'2',
			'parent':'中信出版集团'
		},	
		{
			'img':'img/B12.jpg',
			'auther':'侧侧轻寒',
			'title':'光芒记',
			'money':'¥9.99',
			'pid':'2',
			'parent':'中信出版集团'
		}
		],
	
		rend:[
		{
			'img':'img/B13.jpg',
			'auther':'李梦',
			'title':'绘画中的日常',
			'money':'¥8.82',
			'pid':'3',
			'parent':'华章数字传媒'
		},		
		{
			'img':'img/B14.jpg',
			'auther':'由巴斯树',
			'title':'听说你还记得我',
			'money':'¥3.99'	,
			'pid':'3',
			'parent':'华章数字传媒'
		},				
		{
			'img':'img/B15.jpg',
			'auther':'盖里.陶比斯',
			'title':'我们为什么会发胖',
			'money':'¥27.29',
			'pid':'3',
			'parent':'华章数字传媒'
		},			
		{
			'img':'img/B16.jpg',
			'auther':'唐达天',
			'title':'二把手',
			'money':'¥7.20',
			'pid':'3',
			'parent':'华章数字传媒'
		},			
		{
			'img':'img/B17.jpg',
			'auther':'陈颖君',
			'title':'补气血：中医养生智慧',
			'money':'¥2',
			'pid':'4',
			'parent':'磨铁中文网'
		},			
		{
			'img':'img/B18.jpg',
			'auther':'【美】基斯.法拉',
			'title':'别独自用餐',
			'money':'¥32.20',
			'pid':'4',
			'parent':'磨铁中文网'
		},								
		{
			'img':'img/B19.jpg',
			'auther':'慕容雪村',
			'title':'慕容雪村经典文集',
			'money':'¥9.98',
			'pid':'4',
			'parent':'磨铁中文网'
		},								
		{
			'img':'img/B20.jpg',
			'auther':'谈婧',
			'title':'重新定义分享',
			'money':'¥12.60',
			'pid':'4',
			'parent':'磨铁中文网'
		},								
		{
			'img':'img/B21.jpg',
			'auther':'谈婧',
			'title':'互联网+：创下2.0下的经济格局',
			'money':'¥8.00',
			'pid':'5',
			'parent':'长江新世纪'
		},								
		{
			'img':'img/B22.jpg',
			'auther':'籽月',
			'title':'蔚然成风',
			'money':'¥2.99',
			'pid':'5',
			'parent':'长江新世纪'
		},								
		{
			'img':'img/B23.jpg',
			'auther':'达芙妮.杜姆里',
			'title':'浮生梦',
			'money':'¥9.99',
			'pid':'5',
			'parent':'长江新世纪'
		},								
		{
			'img':'img/B24.jpg',
			'auther':'【美】弗兰克.',
			'title':'沙丘',
			'money':'¥38.08',
			'pid':'5',
			'parent':'长江新世纪'
		}																
	],
	Cu:[
		{
			'img':'img/B25.jpg',
			'auther':'唐七',
			'title':'岁月是朵两生花',
			'money':'¥5.60',
			'pid':'6',
			'parent':'博集天卷'
		},
		{
			'img':'img/B26.jpg',
			'auther':'唐七',
			'title':'三生三世十里桃花',
			'money':'¥5.60',
			'pid':'6',
			'parent':'博集天卷'
		},
		{
			'img':'img/B27.jpg',
			'auther':'唐七',
			'title':'三生三世枕上书',
			'money':'¥6.39',
			'pid':'6',
			'parent':'博集天卷'
		},
		{
			'img':'img/B28.jpg',
			'auther':'马薇薇',
			'title':'好好说话',
			'money':'¥20.58',
			'pid':'6',
			'parent':'博集天卷'
		},
		{
			'img':'img/B29.jpg',
			'auther':'杨波',
			'title':'轻松学C++语言',
			'money':'¥3.99',
			'pid':'7',
			'parent':'果麦'
		},
		{
			'img':'img/B30.jpg',
			'auther':'雅趣编辑部',
			'title':'香槟偏偏可以配上你',
			'money':'¥1.99',
			'pid':'7',
			'parent':'果麦'
		},
		{
			'img':'img/B31.jpg',
			'auther':'蛇从革',
			'title':'大宗师：长江之战',
			'money':'¥8.99',
			'pid':'7',
			'parent':'果麦'
		},
		{
			'img':'img/B32.jpg',
			'auther':'李延鹏',
			'title':'轻松学ARM嵌入式开发',
			'money':'¥3.99',
			'pid':'7',
			'parent':'果麦'
		},
		{
			'img':'img/B33.jpg',
			'auther':'',
			'title':'中医药文化：2016年6期',
			'money':'¥3.99',
			'pid':'8',
			'parent':'理想国'
		},
		{
			'img':'img/B34.jpg',
			'auther':'武宏志',
			'title':'身体知道答案',
			'money':'¥12.05',
			'pid':'8',
			'parent':'理想国'
		},
		{
			'img':'img/B35.jpg',
			'auther':'周华',
			'title':'教你如何实现财务自由',
			'money':'¥10.05',
			'pid':'8',
			'parent':'理想国'
		},
		{
			'img':'img/B36.jpg',
			'auther':'悟君居士',
			'title':'"缠中说禅"股市技术理论',
			'money':'¥19.80',
			'pid':'8',
			'parent':'理想国'
		},
	],
	componey:[
	{
		'img':'img/P01.jpg',
		'parent':'新星出版社',
		'id':'0'
	},
	{
		'img':'img/P02.jpg',
		'parent':'读客',
		'id':'1'
	},
	{
		'img':'img/P03.jpg',
		'parent':'中信出版集团',
		'id':'2'
	},
	{
		'img':'img/P04.jpg',
		'parent':'华章数字传媒',
		'id':'3'
	},
	{
		'img':'img/P05.jpg',
		'parent':'磨铁中文网',
		'id':'4'
	},
	{
		'img':'img/P06.jpg',
		'parent':'长江新世纪',
		'id':'5'
	},
	{
		'img':'img/P07.jpg',
		'parent':'博集天卷',
		'id':'6'
	},
	{
		'img':'img/P08.jpg',
		'parent':'果麦',
		'id':'7'
	},
	{
		'img':'img/P09.jpg',
		'parent':'理想国',
		'id':'8'
	}
	]
		
}								
var Cphoto = {
	'name':'Design,Planning',
	photo:[
		{
			'img':'img/tu01.jpg',
			'title':'UI/LOGO/WEB',
			'font':"LETSRACE"
		},
		{
			'img':'img/tu02.jpg',
			'font':'KUANGZHEN',
			'title':'WEB DESIGN'
		},
		{
			'img':'img/tu03.jpg',
			'font':'QBAKERY',
			'title':'WEB DESIGN'
		},
		{
			'img':'img/tu04.jpg',
			'font':'KAPOK',
			'title':'VI DESIGN'
		},
		{
			'img':'img/tu05.jpg',
			'font':'YONG',
			'title':'VI DESIGN'
		},
		{
			'img':'img/tu06.jpg',
			'font':'YONG',
			'title':'WEB DESIGN'
		},
		{
			'img':'img/tu07.jpg',
			'font':'SHINESUN',
			'title':'APP DESIGN'
		},
		{
			'img':'img/tu08.jpg',
			'font':'VANDODO',
			'title':'WEB DESGIN'
		},
		{
			'img':'img/tu09.jpg',
			'font':'YONG',
			'title':'APP DESIGN'
		},
		{
			'img':'img/tu10.jpg',
			'font':'SHINESUN',
			'title':'WEB DESGIN'
		},
		{
			'img':'img/tu11.jpg',
			'font':'VANDODO',
			'title':'WEB DESGIN'
		},
		{
			'img':'img/tu14.jpg',
			'font':'INOUT',
			'title':'VI DESIGN'
			
		},
		{
			'img':'img/tu16.jpg',
			'font':'SHIATANG',
			'title':'VI DESIGN'
		},
		{
			'img':'img/tu17.jpg',
			'font':'T-MASTER',
			'title':'WEB DESGIN'
		},
		{
			'img':'img/tu00.jpg',
			'font':'LIZIBA',
			'title':'WEB DESGIN'
		},
		{
			'img':'img/ctu13.jpg',
			'font':'LIZIBA',
			'title':'WEB DESGIN'
		}
	]
}
							